name: wakatime-stats

on:
#   schedule:
#     - cron: '30 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "False"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: ":zap: Update wakatime activity"
          SHOW_LOC_CHART: "False"
          LOCALE: "vn"
          SHOW_LINES_OF_CODE: "True"
          
