name: update-gh-activity

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}        
        env:
          token: ${{ secrets.GH_TOKEN }}
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: ":zap: Update github activity yep"
